name: IOT IJK ANDROID RELEASE CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download r27 NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r27-darwin-x86_64.zip
          unzip android-ndk-r27-darwin-x86_64.zip
      - name: Update SDK Version
        run: |
          rtt=$(git describe --tags `git rev-list --tags --max-count=1`)
          rt=${rtt#*v}
          rc=$(git rev-parse --short HEAD)
          cd android/ijkplayer
          sed -i "" 's#def version.*#def version = \"'$rt'\"#g' config.gradle
      - uses: actions/setup-java@v4
        with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '11'
      - name: Build with Gradle
        run: |
          ls -l /Users/runner/work/ijkplayer-android/ijkplayer-android/android-ndk-r27
          perl -i -pe "s#.*HOST_ARCH=x86_64.*#\t\tx86_64|amd64|arm64) HOST_ARCH=x86_64;;#g" /Users/runner/work/ijkplayer-android/ijkplayer-android/android-ndk-r27/ndk-build
          export ANDROID_NDK=/Users/runner/work/ijkplayer-android/ijkplayer-android/android-ndk-r27
          export ANDROID_NDK_ROOT=/Users/runner/work/ijkplayer-android/ijkplayer-android/android-ndk-r27
          
          ./init-android-openssl.sh
          ./init-android.sh

          cd android/contrib
          ./compile-openssl.sh arm64
          ./compile-ffmpeg.sh clean
          ./compile-ffmpeg.sh arm64
          cd ..
          ./compile-ijk.sh arm64

          cd contrib
          ./compile-openssl.sh armv7a
          ./compile-ffmpeg.sh clean
          ./compile-ffmpeg.sh armv7a
          cd ..
          ./compile-ijk.sh armv7a
          
          cd android/ijkplayer
          ./gradlew :ijkplayer-armv7a:assemble
          ./gradlew :ijkplayer-arm64:assemble
          ./gradlew :ijkplayer-java:assemble
          
      - name: Upload Node Directory
        uses: actions/upload-artifact@v4
        with:
          name: ijk
          path: /Users/runner/work/iot-ijkplayer
