name: IOT IJK ANDROID RELEASE CI

on:
  workflow_dispatch:
env:
  ROOT: /home/runner/work/ijkplayer-android
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        
      - name: Download r27c NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip
          unzip android-ndk-r27c-linux.zip

      - name: Build ffmpeg
        run: |
          ls -l ${{ env.ROOT }}/android-ndk-r27c
          perl -i -pe "s#.*HOST_ARCH=x86_64.*#\t\tx86_64|amd64|arm64) HOST_ARCH=x86_64;;#g" ${{ env.ROOT }}/android-ndk-r27c/ndk-build
          export ANDROID_NDK=${{ env.ROOT }}/android-ndk-r27c
          export ANDROID_NDK_ROOT=${{ env.ROOT }}/android-ndk-r27c
          cd ${{ env.ROOT }}
          ./init-android-openssl.sh
          ./init-android.sh

          cd android/contrib
          ./compile-openssl.sh arm64
          ./compile-ffmpeg.sh clean
          ./compile-ffmpeg.sh arm64
          cd ..
          ./compile-ijk.sh arm64

          cd contrib
          ./compile-openssl.sh armv7a
          ./compile-ffmpeg.sh clean
          ./compile-ffmpeg.sh armv7a
          cd ..
          ./compile-ijk.sh armv7a
          
      - name: Upload Node Directory
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-6.1.1
          path: ${{ env.ROOT }}/android/contrib
          
